# Generated by Django 5.1.4 on 2025-01-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillflow', '0003_weeklyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='schedule_type',
            field=models.CharField(choices=[('recurring', 'Recurring'), ('single', 'Single')], default='recurring', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
